language: c
dist: trusty

sudo: false

cache:
  apt: true

addons:
  apt:
    packages:
      - gfortran
      - binutils
      - lcov

install:
  - mkdir build && cd build
  - cmake ..
  - make VERBOSE=1

script:
  - ctest -V
