language: c
dist: trusty

deploy:
  - provider: pages
  - skip-cleanup: true
  - github-token: $GITHUB_TOKEN
  - on:
      branch: gh-pages
  - local-dir: doc

sudo: false

cache:
  apt: true

addons:
  apt:
    packages:
      - gfortran
      - binutils
      - lcov
      - doxygen

install:
  - mkdir build && cd build
  - cmake ..
  - make VERBOSE=1
  - cd ..
  - mkdir build_coverage && cd build_coverage
  - cmake .. -DCMAKE_Fortran_FLAGS='--coverage' -DWITH_DOXYGEN=ON
  - make
  - make test
  - make doc
  - lcov -c -d . -o ft_coverage.info
  - genhtml ft_coverage.info --output-directory doc/ft_coverage

script:
  - ctest -V
